### ISSUE TITLE
warn_if_match and warn_unless match problem

### ISSUE THREAD

**Issue by nowinter** [dod38fr/config-model#2]
the run_regexp_set_on_value sub callback is set to compare $\_\[0\] to $rxp
I think it should be $$value (which is the value) instead of $\_\[0\] (which is the Value object)

**Comment by dod38fr** [comment]
Hmm. Looks like you're right. I need to check why the tests pass...

**Comment by nowinter** [comment]
Ooops, sorry, you are right! This is not an issue

**Comment by dod38fr** [comment]
no problem. I'm glad to find out that some people are reading my code :-)
