### ISSUE TITLE
fstab: `suid`/`nosuid` are valid options for vfat

### ISSUE THREAD

**Issue by topimiettinen** [dod38fr/config-model#30]
I get this error with `cme check fstab`:
```
object 'fs:"/efi" fs_mntopts' error: unknown element 'suid'. Either your file has an error or Fstab::CommonOptions model is lagging behind. In the latter case, please submit a bug report to https://github.com/dod38fr/config-model/issues. See cme man page for details.
        Expected elements: 'async','atime','auto','dev','exec','group','mand','user','defaults','rw','relatime'
```

VFAT file system `/efi` is mounted with options `ro,nosuid,nodev,noexec,noatime,noauto,umask=077`. According to [mount(8)](https://man7.org/linux/man-pages/man8/mount.8.html), `suid` and `nosuid` are valid options for vfat (though they don't do anything useful since vfat can't store setuid/setgid bits, FS capabilities or extended attributes used by SELinux).

Maybe [/lib/Config/Model/models/Fstab/CommonOptions.pl#L49](https://github.com/dod38fr/config-model/blob/3d1f2edc93c170bf73078c9675481880da019b19/lib/Config/Model/models/Fstab/CommonOptions.pl#L49) should include something like:
```
      'suid',
      {
        'type' => 'leaf',
        'value_type' => 'boolean'
      },
```

**Comment by dod38fr** [comment]
Indeed. Would you care to fix this ?

I've created  branch `fix-missing-suid` with a test that fails on this problem.

I'd suggest to use `cme meta edit` to update the model. See https://github.com/dod38fr/config-model/wiki/How-to-add-a-new-parameter-to-an-existing-model for a model modification example.

**Comment by topimiettinen** [comment]
OK, made PR #31.

I used `cme meta edit` but it didn't make any difference.

**Comment by dod38fr** [comment]
Thanks. 

I've seen that I've forgotten to add a description to the elements of `FStab::CommonOptions`. I'll should fix this before next release. These descriptions are shown as documentation when using `cme edit`, a GUI without integrated doc is less useful.

Thanks for the PR.
