### ISSUE TITLE
Exception::Class was not removed completly

### ISSUE THREAD

**Issue by jplesnik** [dod38fr/config-model#5]
The Exception::Class is still used in Config::Model::Warper

`lib/Config/Model/Warper.pm:`
`L569:        if ( my $e = Exception::Class->caught($expected_error) ) {`

Is it correct or should it be replaced?

**Comment by dod38fr** [comment]
Oops... It should be replaced.

Thanks for the heads-up

**Comment by dod38fr** [comment]
@jplesnik I'd like to know how you found this issue. Was it by reading code or did you get an error ?

All the best

**Comment by jplesnik** [comment]
I was updating Fedora package to the latest version. Before I removed Exception::Class from build-requires, I just checked via grep if Exception::Class is no using in code. 
I did not get any error.

**Comment by dod38fr** [comment]
Interesting. I did not know that Config::Model was now up-to-date on Fedora. That's very good news. :smiley: 

I'll fix this issue asap (I need to check whether this code is dead or not).

BTW, feel free to ask for changes that may ease your work as fedora packager (As Debian packager, I know that upstream can help a lot in our day-to-day activities)

All the best

**Comment by dod38fr** [comment]
Fixed in v2.079
